from pathlib import Path
from datetime import datetime

from docx import Document
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
)
from reportlab.lib.styles import getSampleStyleSheet


REPORT_DIR = Path("reports")
REPORT_DIR.mkdir(
    exist_ok=True
)


def build_report(
    project_name,
    files_count,
    chunks_count,
    embedding_model,
    llm_model,
    security_summary="Not Scanned",
    documentation_summary="Not Generated",
    ai_summary="No AI Summary Available"
):
    """
    Creates the report text.
    """

    report = f"""
# CodePilot AI Report

Generated On:
{datetime.now().strftime("%d %B %Y %H:%M")}

---

## Project

{project_name}

---

## Repository Statistics

Files Indexed : {files_count}

Code Chunks : {chunks_count}

Embedding Model : {embedding_model}

LLM : {llm_model}

---

## Documentation

{documentation_summary}

---

## Security

{security_summary}

---

## AI Summary

{ai_summary}

---

Generated by CodePilot AI
"""

    return report


# -----------------------------------
# Markdown
# -----------------------------------

def export_markdown(
    report_text,
    project_name
):

    file_path = REPORT_DIR / f"{project_name}.md"

    with open(
        file_path,
        "w",
        encoding="utf-8"
    ) as file:

        file.write(report_text)

    return file_path


# -----------------------------------
# PDF
# -----------------------------------

def export_pdf(
    report_text,
    project_name
):

    file_path = REPORT_DIR / f"{project_name}.pdf"

    styles = getSampleStyleSheet()

    document = SimpleDocTemplate(
        str(file_path)
    )

    story = []

    for line in report_text.split("\n"):

        story.append(
            Paragraph(
                line,
                styles["BodyText"]
            )
        )

    document.build(story)

    return file_path


# -----------------------------------
# DOCX
# -----------------------------------

def export_docx(
    report_text,
    project_name
):

    file_path = REPORT_DIR / f"{project_name}.docx"

    document = Document()

    document.add_heading(
        "CodePilot AI Report",
        level=1
    )

    document.add_paragraph(
        report_text
    )

    document.save(
        file_path
    )

    return file_path